const Chance = require("chance"); //genera datos aleatoriamente, para llenar los campos de la BD
const chance = new Chance();

const fakeUserPostsData = [
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
  [chance.sentence(), chance.integer({ min: 1, max: 40 }), chance.paragraph()],
];

module.exports = {
  fakeUserPostsData,
};
