const Chance = require("chance"); //genera datos aleatoriamente, para llenar los campos de la BD
const chance = new Chance();

const fakeUserData = [
  [
    "jsarabialugo@gmail.com",
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [1, 2],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [3, 4],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [5, 6],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [7, 8],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [9, 10],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [11, 12],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [13, 14],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [15, 16],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [17, 18],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [19, 20],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [21, 22],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [23, 24],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [25, 26],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [27, 28],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [29, 30],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [31, 32],
    1,
  ],
  [
    chance.email(),
    chance.company() + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [33, 34],
    1,
  ],
];

module.exports = {
  fakeUserData,
};
