const Chance = require("chance"); //genera datos aleatoriamente, para llenar los campos de la BD
const chance = new Chance();

const fakeUserData = [
  [
    "jsarabialugo@gmail.com",
    "Winn Dixie Stores Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [1, 2],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Avon Products, Inc." + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [3, 4],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Aon Corporation" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [5, 6],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Lam Research Corporation" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [7, 8],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Union Planters Corp" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [9, 10],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "NSTAR" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [11, 12],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Calpine Corp" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [13, 14],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "National Service Industries Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [15, 16],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "ALLETE, Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [17, 18],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Archer Daniels Midland" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [19, 20],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Harley-Davidson Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [21, 22],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Murphy Oil Corporation" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [23, 24],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Amerada Hess Corporation" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [25, 26],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Unified Western Grocers Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [27, 28],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "AdvancePCS, Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [29, 30],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "AmSouth Bancorp" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [31, 32],
    chance.integer({ min: 0, max: 2 }),
  ],
  [
    chance.email(),
    "Universal Forest Products Inc" + " company",
    chance.integer({ min: 10000000, max: 99999999 }),
    chance.name(),
    chance.address(),
    chance.url(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.country({ full: true }),
    chance.sentence(),
    [33, 34],
    chance.integer({ min: 0, max: 2 }),
  ],
];

module.exports = {
  fakeUserData,
};
