const Chance = require("chance"); //genera datos aleatoriamente, para llenar los campos de la BD
const chance = new Chance();

const fakeUserData = [
  [
    "t0mshaster5@gmail.com",
    "Gregory Jenkins",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "CSS3", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Daisy Chavez",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "JavaScript"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Catherine Lindsey",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java", "C#"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Daniel Tate",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Donald Watson",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["MySQL", "Java", "Python"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Ronald Lamb",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "JavaScript", "C"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Philip Carpenter",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java", "C#", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Cole Kelly",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["PostgreSQL", "MongoDB", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Jerome Colon",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "CSS3", "C#", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Anthony Graham",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Bobby Ramsey",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Lilly Ray",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "MongoDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Helen Russell",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Patrick Thornton",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Mario Fuentes",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "C#", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Eugenia Chavez",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "MongoDB", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Genevieve Cole",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "MongoDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Glen Holmes",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Gussie McCarthy",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "MongoDB", "Java", "CSS3"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Herbert Simpson",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "CSS3", "Java", "C"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Howard Allison",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "JavaScript", "SQLite", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Jeanette Franklin",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java", "Python", "C"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Jesse Swanson",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "MySQL", "MariaDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "John Valdez",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["MySQL", "Java", "Python"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Jonathan Singleton",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "MongoDB", "PostgreSQL", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Lucille Murray",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java", "MongoDB", "JavaScript", "Oracle"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Elizabeth Larson",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["PostgreSQL", "Java"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Mamie Wheeler",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["HTML", "C#", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Mark Stone",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Max Cohen",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Oracle", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Michael Drake",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Mittie Gross",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "Oracle", "SQLite"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Nell Richardson",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Olive Sandoval",
    "empleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C#"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Ora Hunt",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "Java", "SQLite", "MySQL", "MariaDB", "PostgreSQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],

  [
    chance.email(),
    "Ralph Alvarez",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "MariaDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Tom Lindsey",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#", "Java", "SQLite"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Vernon Smith",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["JavaScript", "Python", "C#", "HTML"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Willie Flowers",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "MongoDB", "Oracle", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    chance.email(),
    "Leona Henderson",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "MongoDB", "Oracle", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioMartinez@gmail.com",
    "Juan Pablo Martinez",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "MongoDB", "Oracle", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioHernandez@gmail.com",
    "Ana Maria Hernandez",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["SQLite", "MongoDB", "MySQL"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioCastiblanco@gmail.com",
    "Dario Nicolas Castiblanco",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "MariaDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioZamudio@gmail.com",
    "Diego Esteban Zamudio",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Python", "MariaDB"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioTriana@gmail.com",
    "Angie tatiana Triana",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["C", "C#", "Java", "SQLite"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
  [
    "usuarioRios@gmail.com",
    "Karen Eleana Rios",
    "desempleado",
    chance.age(),
    chance.url({ extensions: ["jpg", "png"] }),
    chance.sentence(),
    ["Java", "SQLite"],
    chance.country({ full: true }),
    chance.domain(),
    chance.url({ extensions: ["pdf"] }),
    chance.integer({ min: 0, max: 2 })
  ],
];

module.exports = {
  fakeUserData,
};
